// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 9An8zqKqHunPYYo4cu2raH
// Component: oWqYNAhSlk

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_jean_survey_2.module.css"; // plasmic-import: 9An8zqKqHunPYYo4cu2raH/projectcss
import sty from "./PlasmicShortAnswer.module.css"; // plasmic-import: oWqYNAhSlk/css

export type PlasmicShortAnswer__VariantMembers = {};
export type PlasmicShortAnswer__VariantsArgs = {};
type VariantPropType = keyof PlasmicShortAnswer__VariantsArgs;
export const PlasmicShortAnswer__VariantProps = new Array<VariantPropType>();

export type PlasmicShortAnswer__ArgsType = {};
type ArgPropType = keyof PlasmicShortAnswer__ArgsType;
export const PlasmicShortAnswer__ArgProps = new Array<ArgPropType>();

export type PlasmicShortAnswer__OverridesType = {
  saContainer?: p.Flex<"div">;
};

export interface DefaultShortAnswerProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicShortAnswer__RenderFunc(props: {
  variants: PlasmicShortAnswer__VariantsArgs;
  args: PlasmicShortAnswer__ArgsType;
  overrides: PlasmicShortAnswer__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});

  return (
    <div
      data-plasmic-name={"saContainer"}
      data-plasmic-override={overrides.saContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.saContainer
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  saContainer: ["saContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  saContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShortAnswer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShortAnswer__VariantsArgs;
    args?: PlasmicShortAnswer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicShortAnswer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicShortAnswer__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicShortAnswer__ArgProps,
          internalVariantPropNames: PlasmicShortAnswer__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicShortAnswer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "saContainer") {
    func.displayName = "PlasmicShortAnswer";
  } else {
    func.displayName = `PlasmicShortAnswer.${nodeName}`;
  }
  return func;
}

export const PlasmicShortAnswer = Object.assign(
  // Top-level PlasmicShortAnswer renders the root element
  makeNodeComponent("saContainer"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicShortAnswer
    internalVariantProps: PlasmicShortAnswer__VariantProps,
    internalArgProps: PlasmicShortAnswer__ArgProps
  }
);

export default PlasmicShortAnswer;
/* prettier-ignore-end */
